### ISSUE TITLE
trying to color qqplot points

### ISSUE THREAD

**Issue by elsadebecker** [stephenturner/qqman#57]
I'd like to color QQ-plot points by arbitrary categories. I know this isn't supported by qqman itself, but I thought I could do it using basic R plotting. To test this out, I tried to color them by chromosome 
`qq(gwasResults$P, col = factor(gwasResults$CHR), main="Color by CHR")
`
![screen shot 2017-08-17 at 10 40 31 am](https://user-images.githubusercontent.com/29153253/29417910-c6ee4c5e-8338-11e7-81cf-989e66a6e32c.png)

and pvalue
`gwasResults$INT=1`
`gwasResults$INT[gwasResults$P<.5]=2`
`qq(gwasResults$P, col = gwasResults$INT, main= "Color by INT")`
![screen shot 2017-08-17 at 10 40 45 am](https://user-images.githubusercontent.com/29153253/29417880-ab79f32e-8338-11e7-8004-2031f113c3e3.png)

Why is it that when I try to color by chromosome, I get 22 bands of color that don't correspond to chromosome at all, and when I try to color by pvalue, I get 2 colors seemingly randomly distributed throughout the plot?

If the answer is "because you shouldn't try to do this, find another package" that's fine. I'm just curious.

**Comment by stephenturner** [comment]
Hm. It's been so long since I've written any code using base R graphics I forget how to color code points. Confirming that plotting the points by chromosome, does work:

```r
plot(gwasResults$P, col=factor(gwasResults$CHR))
```

![image](https://user-images.githubusercontent.com/460076/29431352-a39dfcae-8365-11e7-869d-c053006cb261.png)

I think if you look at the code for `qq()`:

```r
function (pvector, ...) 
{
    if (!is.numeric(pvector)) 
        stop("Input must be numeric.")
    pvector <- pvector[!is.na(pvector) & !is.nan(pvector) & !is.null(pvector) & 
        is.finite(pvector) & pvector < 1 & pvector > 0]
    o = -log10(sort(pvector, decreasing = FALSE))
    e = -log10(ppoints(length(pvector)))
    def_args <- list(pch = 20, xlim = c(0, max(e)), ylim = c(0, 
        max(o)), xlab = expression(Expected ~ ~-log[10](italic(p))), 
        ylab = expression(Observed ~ ~-log[10](italic(p))))
    dotargs <- list(...)
    tryCatch(do.call("plot", c(list(x = e, y = o), def_args[!names(def_args) %in% 
        names(dotargs)], dotargs)), warn = stop)
    abline(0, 1, col = "red")
}
```

You see that line where the observed values are sorted: `o = -log10(sort(pvector, decreasing = FALSE))`. This throws the color-coding off sync. You'd probably need to do something like `dplyr::arrange` on the pvector, and remove the `sort` call from the function.
